### ISSUE TITLE
Use cosmetic NumberFormat() to display slow performance time

### ISSUE THREAD

**Issue by JamoCA** [kwaschny/cf_performance#1]
If you want to prettify the performance time and make it easier to read, you can use numberformat().  _Apparently adding a single "thousands" comma is enough to repeat to pattern, but behind the decimal you need to add a bunch of placeholders and then trim the trailing 0's.)_

Here's a function
```
<cfscript>
string function prettyDecimal(numeric inputString=0){
	return trim(REReplace(numberformat(val(arguments.inputString), '9,999.999999999999'), "0+$", ""));
}
</cfscript>
```

NOTE: Some developers may want to perform additional functions if performance it slow. I tend only use timing during development and use it cosmetically.  As a result, you may want to enable this as an option (similar to the "nano" option.)

**Comment by kwaschny** [comment]
What do you mean by "easier to read"? Unless you specify the time unit, the output will automatically adjust from milliseconds to seconds, if 4 digits are exceeded (> 10 seconds). Adding a thousand separator to a number that already has 4 decimal places doesn't feel right. I prefer `9876.5432` over `9,876.5432`.
